begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
select is((select count(*) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','private') and c.relkind='r' and not c.relrowsecurity),0::bigint,'all application and private tables have RLS');
select is((select count(*) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','private') and c.relkind='r' and has_table_privilege('anon',c.oid,'SELECT,INSERT,UPDATE,DELETE')),0::bigint,'anonymous has no application table grants');
select is((select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','private') and p.prosecdef and not exists(select 1 from unnest(p.proconfig) c where c like 'search_path=%')),0::bigint,'every definer pins search_path');
select is((select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','private') and has_function_privilege('anon',p.oid,'EXECUTE')),0::bigint,'anonymous cannot execute application functions');
select is((select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','private') and p.prorettype='trigger'::regtype and has_function_privilege('authenticated',p.oid,'EXECUTE')),0::bigint,'trigger functions cannot be called by clients');
select ok(not has_table_privilege('authenticated','private.storage_cleanup','SELECT,INSERT,UPDATE,DELETE'),'cleanup queue has no client grants');
select ok(not has_table_privilege('authenticated','public.activities','INSERT,UPDATE,DELETE'),'audit log is read-only');
select is((select count(*) from storage.buckets where id in ('avatars','task-attachments') and public),0::bigint,'application buckets stay private');
select ok(not has_function_privilege('authenticated','public.claim_storage_cleanup()','EXECUTE'),'worker claims restricted');
select ok(not has_function_privilege('authenticated','public.complete_storage_cleanup(text,uuid)','EXECUTE'),'worker acknowledgements restricted');
select ok(not has_column_privilege('authenticated','public.tasks','workspace_id','UPDATE'),'task tenant cannot be changed');
select ok(not has_column_privilege('authenticated','public.profiles','id','UPDATE'),'profile identity cannot be changed');
select ok(not has_column_privilege('authenticated','public.workspaces','owner_id','UPDATE'),'workspace ownership cannot be forged');
insert into auth.users(id,email) values('a0000000-0000-0000-0000-000000000001','audit-owner@example.test'),('a0000000-0000-0000-0000-000000000002','audit-outsider@example.test');
insert into public.profiles(id,name,username) values('a0000000-0000-0000-0000-000000000001','Audit owner','audit_owner'),('a0000000-0000-0000-0000-000000000002','Audit outsider','audit_outsider');
insert into public.workspaces(id,name,owner_id) values('a0000000-0000-0000-0000-000000000010','Audit workspace','a0000000-0000-0000-0000-000000000001');
insert into public.boards(workspace_id,name,position) select 'a0000000-0000-0000-0000-000000000010','Audit board '||n,n from generate_series(1,6) n;
set local role authenticated;
select set_config('request.jwt.claim.sub','a0000000-0000-0000-0000-000000000001',true);
select is((select board_count from public.workspace_summaries() where workspace_id='a0000000-0000-0000-0000-000000000010'),6::bigint,'summary counts all boards');
select is((select jsonb_array_length(recent_boards) from public.workspace_summaries() where workspace_id='a0000000-0000-0000-0000-000000000010'),4,'summary transfers only four recent boards');
select set_config('request.jwt.claim.sub','a0000000-0000-0000-0000-000000000002',true);
select is((select count(*) from public.workspace_summaries()),0::bigint,'summary does not expose outsider data');
reset role;
select * from finish();
rollback;
